// <auto-generated />
namespace EmailSenderAspNetMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202212022210 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202212022210));
        
        string IMigrationMetadata.Id
        {
            get { return "202212022110118_202212022210"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
