// <auto-generated />
namespace EmailSenderAspNetMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202211191331 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202211191331));
        
        string IMigrationMetadata.Id
        {
            get { return "202211191231368_202211191331"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
